package com.example.w22borg.data;

import org.jetbrains.annotations.Contract;

import java.io.Serializable;
import java.time.LocalDate;
import java.util.Objects;

public class EmployeeModel implements Serializable {

    private int id; // autogenerated value that the user will not be interacting with
    private int isAnActiveEmployee;
    private String firstName;
    private String lastName;

    private String email;
    private String phoneNumber;

    private String dateOnStartingJob; // change this into something to be used with the built-in Calendar library
    private int totalWorkingShiftsSinceStartDate;

    private boolean canOpenStore;
    private boolean canCloseStore;
    private int mon, tue, wed, thu, fri, sat, sun; //employee availability
                                                    //0 = can open and close, 1 = open, 2 = close, 3 = unavailable


    //constructors
    // add employee constructor, default training to none and availability to none
    public EmployeeModel(int id, String firstName, String lastName, String email, String phoneNumber, String dateOnStartingJob) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.phoneNumber = phoneNumber;
        this.dateOnStartingJob = dateOnStartingJob;
        this.totalWorkingShiftsSinceStartDate = 0;
        this.canOpenStore = false;
        this.canCloseStore = false;
        this.mon = this.tue = this.wed = this.thu = this.fri = this.sat = this.sun = 3;
    }

    // full database information for employees
    public EmployeeModel(int id, String firstName, String lastName, String email, String phoneNumber,
                         String dateOnStartingJob, int totalWorkingShiftsSinceStartDate, boolean canOpenStore, boolean canCloseStore, int isAnActiveEmployee,
                         int mon, int tue, int wed, int thu, int fri, int sat, int sun) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.phoneNumber = phoneNumber;
        this.dateOnStartingJob = dateOnStartingJob;
        this.totalWorkingShiftsSinceStartDate = totalWorkingShiftsSinceStartDate;
        this.canOpenStore = canOpenStore;
        this.canCloseStore = canCloseStore;
        this.isAnActiveEmployee = isAnActiveEmployee;
        this.mon = mon;
        this.tue = tue;
        this.wed = wed;
        this.thu = thu;
        this.fri = fri;
        this.sat = sat;
        this.sun = sun;
    }

    public EmployeeModel(int id, String firstName, String lastName, String dateOnStartingJob, boolean canOpenStore, boolean canCloseStore) {
        this.id = id;
        this.isAnActiveEmployee = 0;
        this.firstName = firstName;
        this.lastName = lastName;
        this.dateOnStartingJob = dateOnStartingJob;
        this.totalWorkingShiftsSinceStartDate = 0;
        this.canOpenStore = canOpenStore;
        this.canCloseStore = canCloseStore;
    }

    public EmployeeModel(int id, String firstName, String lastName, String dateOnStartingJob) {
        this.id = id;
        this.isAnActiveEmployee = 0;
        this.firstName = firstName;
        this.lastName = lastName;
        this.dateOnStartingJob = dateOnStartingJob;
        this.totalWorkingShiftsSinceStartDate = 0;
        this.canOpenStore = false;
        this.canCloseStore = false;
    }

    public EmployeeModel(int empID, String empFirstName, String empLastName) {
        this.isAnActiveEmployee = -1;
        this.totalWorkingShiftsSinceStartDate = 0;
        this.canOpenStore = false;
        this.canCloseStore = false;
    }

    // CLONE
    public EmployeeModel(EmployeeModel clone) {
        this.id = clone.getId();
        this.isAnActiveEmployee = clone.getIsAnActiveEmployee();
        this.firstName = clone.getFirstName();
        this.lastName = clone.getLastName();
        this.dateOnStartingJob = clone.getDateOnStartingJob();
        this.totalWorkingShiftsSinceStartDate = clone.getTotalWorkingShiftsSinceStartDate();
        this.canOpenStore = clone.isCanOpenStore();
        this.canCloseStore = clone.isCanCloseStore();
        this.phoneNumber = clone.getPhoneNumber();
        this.email = clone.getEmail();
    }


    // toString for printing employee information

    /*
    @Override
    public String toString() {
        return "EmployeeModel{" +
                "id=" + id +
                ", isAnActiveEmployee=" + isAnActiveEmployee +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", email='" + email + '\'' +
                ", phoneNumber='" + phoneNumber + '\'' +
                ", dateOnStartingJob='" + dateOnStartingJob + '\'' +
                ", totalWorkingShifts=" + totalWorkingShiftsSinceStartDate +
                ", canOpenStore=" + canOpenStore +
                ", canCloseStore=" + canCloseStore +
                '}';
    }
    */



    @Override
    public String toString() {
        StringBuilder returnString = new StringBuilder();
        returnString.append(id + " - " + lastName + ", " + firstName);
        if (canOpenStore && canCloseStore){
            while(returnString.length() < 100){returnString.append(" ");}
            returnString.append("Opener/Closer");
        }
        if (canOpenStore && !canCloseStore){
            while(returnString.length() < 100){returnString.append(" ");}
            returnString.append("Opener");
        }
        if (!canOpenStore && canCloseStore){
            while(returnString.length() < 100){returnString.append(" ");}
            returnString.append("Closer");
        }
        String returnS = returnString.toString();
        return returnS;
    }

    // getters and setters

    public int getId() { return id; }
    public void setId(int id) { this.id = id; }

    public int getIsAnActiveEmployee() { return isAnActiveEmployee; }
    public void setIsAnActiveEmployee(int isAnActiveEmployee) { this.isAnActiveEmployee = isAnActiveEmployee; }

    public String getFirstName() { return firstName; }
    public void setFirstName(String firstName) { this.firstName = firstName; }

    public String getLastName() { return lastName; }
    public void setLastName(String lastName) { this.lastName = lastName; }

    public String getEmail() { return email; }
    public void setEmail(String email) { this.email = email; }

    public String getPhoneNumber() { return phoneNumber; }
    public void setPhoneNumber(String phoneNumber) { this.phoneNumber = phoneNumber; }

    public String getDateOnStartingJob() { return dateOnStartingJob; }
    public void setDateOnStartingJob(String dateOnStartingJob) { this.dateOnStartingJob = dateOnStartingJob; }

    public int getTotalWorkingShiftsSinceStartDate() { return totalWorkingShiftsSinceStartDate; }
    public void setTotalWorkingShiftsSinceStartDate(int totalWorkingShiftsSinceStartDate) { this.totalWorkingShiftsSinceStartDate = totalWorkingShiftsSinceStartDate; }

    public boolean isCanOpenStore() { return canOpenStore; }
    public void setCanOpenStore(boolean canOpenStore) { this.canOpenStore = canOpenStore; }

    public boolean isCanCloseStore() { return canCloseStore; }
    public void setCanCloseStore(boolean canCloseStore) { this.canCloseStore = canCloseStore; }

    public int getMon() { return mon; }
    public void setMon(int mon) { this.mon = mon; }

    public int getTue() { return tue; }
    public void setTue(int tue) { this.tue = tue; }

    public int getWed() { return wed; }
    public void setWed(int wed) { this.wed = wed; }

    public int getThu() { return thu; }
    public void setThu(int thu) { this.thu = thu; }

    public int getFri() { return fri; }
    public void setFri(int fri) { this.fri = fri; }

    public int getSat() { return sat; }
    public void setSat(int sat) { this.sat = sat; }

    public int getSun() { return sun; }
    public void setSun(int sun) { this.sun = sun; }

    @Override
    public boolean equals(Object o) {
        if (!(o instanceof EmployeeModel))
            return false;
        EmployeeModel e = (EmployeeModel) o;
        return Objects.equals(e.getId(), getId());
    }
}